FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env

WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy everything else and publish
COPY . ./
RUN dotnet publish -c Release -o out /p:UseSharedCompilation=false /p:BuildInParallel=true /m:6

# final stage/image
FROM mcr.microsoft.com/dotnet/runtime:7.0

WORKDIR /app

COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Patric.dll"]

