# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /app
COPY main.py .

# Install any needed packages
RUN pip install requests

# Run the application when the container launches
ENTRYPOINT ["python3", "main.py"]
